version: '2'

services:
  relations:    
    container_name: relations
    image: relations
    build: .
    volumes:
      - .:/src
    networks:
      - main_network

  database:
    container_name: relations_db
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
        - "3306"
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        MYSQL_USER: "test_user"
        MYSQL_PASSWORD: "test_pass"
        MYSQL_DATABASE: "relationsDB"
    networks:
        - main_network
        
networks:
  main_network:
    driver: bridge
